[package]
name = "noctalia-system"
description = "System monitors: CPU/mem/disk/net stats, brightness, battery logic, desktop entries."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gio = "0.22.8"
libc = "0.2.189"
noctalia-config = { path = "../noctalia-config" }
noctalia-core = { path = "../noctalia-core" }
noctalia-ipc = { path = "../noctalia-ipc" }

[lints]
workspace = true
