//! Port of `src/core/build_info.{cpp,h}`.
//!
//! `revision()` is generated by `build.rs` at compile time via `git describe
//! --tags --always --dirty=-dirty --abbrev=12` — the same command meson's
//! `vcs_tag()` runs — falling back to `"unknown"` under the same conditions (no
//! git on `PATH`, or the tree isn't a git checkout); see `build.rs` for the
//! fallback logic. No network access either way.
//!
//! `version()` uses Cargo's own package version (`CARGO_PKG_VERSION`, from this
//! crate's `Cargo.toml`) rather than injecting the C++ build's meson
//! `project_version()` (currently `"5.0.0"`) across the migration boundary: the
//! two build systems version independently with no shared source of truth, so
//! this follows the Rust-native convention instead.

const UNKNOWN_REVISION: &str = "unknown";

/// This crate's own version, standing in for the C++ build's compiled-in
/// `NOCTALIA_VERSION` (see module docs for why they're independent numbers).
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// The git revision this binary was built from, or `"unknown"` (see `build.rs`).
pub fn revision() -> &'static str {
    env!("NOCTALIA_GIT_REVISION")
}

/// `"v<version>"`, plus `" (<revision>)"` when the revision is known.
pub fn display_version() -> String {
    let mut label = format!("v{}", version());
    let rev = revision();
    if !rev.is_empty() && rev != UNKNOWN_REVISION {
        label.push_str(" (");
        label.push_str(rev);
        label.push(')');
    }
    label
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn version_is_nonempty() {
        assert!(!version().is_empty());
    }

    #[test]
    fn display_version_never_shows_parenthesized_unknown() {
        assert!(!display_version().contains("(unknown)"));
    }

    #[test]
    fn display_version_matches_version_and_revision() {
        let rev = revision();
        let expected = if rev.is_empty() || rev == UNKNOWN_REVISION {
            format!("v{}", version())
        } else {
            format!("v{} ({rev})", version())
        };
        assert_eq!(display_version(), expected);
    }
}
