[package]
name = "noctalia-theme"
description = "Color/palette/M3 scheme engine, template engine, theme image loading, app-theme outputs."
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
noctalia-core = { path = "../noctalia-core" }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.19"
